# Generated by Django 5.0.1 on 2024-04-12 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saler', '0018_productreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('blog_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('blog_id2', models.CharField(default='', max_length=100)),
                ('blog_title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('pub_date', models.DateField(auto_now=True)),
                ('image1', models.ImageField(default='', null=True, upload_to='blogs/images')),
                ('image2', models.ImageField(blank=True, default='', null=True, upload_to='blogs/images')),
                ('shop', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
