# Generated by Django 5.0.4 on 2024-05-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saler', '0020_blogs_desc2_blogs_desc3_blogs_image3_blogs_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='blog_category',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
